from odoo import models, fields

class FlownTicket(models.Model):
    _name = 'flown.ticket'
    _description = 'Flown Ticket'

    date = fields.Date(string='Date', required=True)
    pnr_alphanumeric = fields.Char(string='PNR alphanumeric')
    iata_ticket_number = fields.Char(string='IATA ticket number')
    iata_ticket_check_digit = fields.Char(string='IATA ticket check digit')
    coupon_order_on_ticket = fields.Char(string='Coupon order on ticket')
    coupon_order_on_segment = fields.Char(string='Coupon order on segment')
    Original_iata_ticket_number = fields.Char(string='Original IATA ticket number')
    Original_iata_ticket_check_digit = fields.Char(string='Original IATA ticket check digit')
    exchanged_iata_ticket_number = fields.Char(string='Exchanged IATA ticket number')
    exchanged_iata_ticket_check_digit = fields.Char(string='Exchanged IATA ticket check digit')
    zenith_coupon_status = fields.Char(string='Zenith coupon status')
    aircraft_type = fields.Char(string='Aircraft type')
    arrival_element = fields.Char(string='Arrival element')
    continuation_element = fields.Char(string='Continuation element')
    class_of_service = fields.Char(string='Class of service')
    airline_designator = fields.Char(string='Airline designator')
    Flight_number = fields.Char(string='Flight number')
    local_dep_datetime = fields.Datetime(string='Local departure date-time')
    local_arr_datetime = fields.Datetime(string='Local arrival date-time')
    departure_airport = fields.Char(string='Departure airport')
    arrival_airport = fields.Char(string='Arrival airport')
    booking_class = fields.Char(string='Booking class')
    coupon_service = fields.Char(string='Coupon service')
    fare_basis_class = fields.Char(string='Fare basis class')
    point_of_sale = fields.Char(string='Point Of sale')
    point_of_sale_code = fields.Char(string='Point Of sale Code')
    payment_type_identifier = fields.Char(string='Payment type identifier')
    customer_name = fields.Char(string='Customer name')
    coupon_price_taxes_commission = fields.Char(string='Coupon price excl. taxes commission (sales currency)')
    coupon_price_taxes = fields.Char(string='Coupon price excl. taxes (sales currency)')
    total_turnover_amount = fields.Char(string='Total turnover amount (sales currency)')
    coupon_commission_amount = fields.Char(string='Coupon commission amount (sales currency)')
    total_taxes_already = fields.Char(string='TotalTaxesAlreadyIncludedinCPNEEquivalentFareWithoutTaxSaleCurrency')
    coupon_taxes_amount = fields.Char(string='Coupon taxes amount (sales currency)')
    iata_taxes_amount = fields.Char(string='IATA taxes amount (sales currency)')
    airline_taxes_amount = fields.Char(string='Airline taxes amount (sales currency)')
    yq_tax_amount = fields.Char(string='YQ tax amount (sales currency)')
    yr_tax_amount = fields.Char(string='YR tax amount (sales currency)')
    service_fee_taxes_amount = fields.Char(string='Service fee taxes amount (Sale currency)')
    issuance_tax_amount = fields.Char(string='Issuance tax amount (Sale currency)')
    total_amount = fields.Char(string='Total amount (sales currency)')
    total_amount_excl = fields.Char(string='Total amount excl. commission (sales currency)')
    coupon_penalty_amount = fields.Char(string='Coupon penalty amount (sales currency)')
    excess_baggage_weight = fields.Char(string='Excess baggage weight')
    excess_baggage_fee_collected = fields.Char(string='Excess baggage fee collected through Zenith (sales currency)')
    acm = fields.Char(string='ACM (sales currency)')
    adm = fields.Char(string='ADM (sales currency)')
    coupon_mileage = fields.Char(string='Coupon mileage')
    ticket_mileage = fields.Char(string='Ticket mileage')
    pnr_of_operating_airline = fields.Char(string='PNR of operating airline')
    designator_of_operating_airline = fields.Char(string='Designator of operating airline')
    flight_number_on_operating_airline = fields.Char(string='Flight number on operating airline')
    booking_class_on_operating_airline = fields.Char(string='Booking class on operating airline')
    pnr_of_marketing_airline = fields.Char(string='PNR of marketing airline')
    designator_of_marketing_airline = fields.Char(string='Designator of marketing airline')
    flight_number_of_marketing_airline = fields.Char(string='Flight number of marketing airline')
    sales_currency = fields.Char(string='Sales currency')
    iata_passenger_type = fields.Char(string='IATA passenger type')
    passenger_civility = fields.Char(string='Passenger civility')
    passenger_surname = fields.Char(string='Passenger surname')
    passenger_first_name = fields.Char(string='Passenger first name')
    datetime_lt_of_issuance = fields.Datetime(string='Date-time (LT) of issuance')
