from odoo import models, fields

class TicketTransaction(models.Model):
    _name = 'ticket.transaction'
    _description = 'Ticket Transaction'

    date = fields.Date(string='Date', required=True)
    name = fields.Char(string='Transaction Name')
    pnr_zenith = fields.Char(string='PNR Zenith')
    record_locator = fields.Char(string='Record Locator')
    heading_st_type = fields.Char(string='Heading (Statment Type)')
    iata_agency_code = fields.Char(string='IATA Agency Code')
    point_of_sales = fields.Char(string='Point of Sales')
    customer = fields.Char(string='Customer')
    payment_type = fields.Char(string='Payment Type')
    balance_sale_currency = fields.Char(string='Balance Sale Currency')
    yq_tax_amount = fields.Char(string='YQ Tax Amount')
    yr_tax_amount = fields.Char(string='YR Tax Amount')
    service_fee_tax_amount = fields.Char(string='Service fee Tax amount')
    insurance_tax_amount = fields.Char(string='Insurance Tax amount')
    other_tax_amount = fields.Char(string='Other Tax amount')
    airline_tax_amount = fields.Char(string='Airline Tax amount')
    iata_tax_amount = fields.Char(string='IATA Tax amount')
    total_tax_amount = fields.Char(string='Total Tax amount')
    sale_agent = fields.Char(string='Sale Agent')
    original_ticket_number = fields.Char(string='Original Ticket Number')
    ticket_number = fields.Char(string='Ticket Number')
    exchanged_ticket_number = fields.Char(string='Exchanged Ticket Number')
    customer_id = fields.Char(string='Customer ID')
    journal_type = fields.Char(string='Journal Type')
    taxes_list = fields.Char(string='Taxes List')
    fair_basis_list = fields.Char(string='Fair Basis List')
    pnr_creator = fields.Char(string='PNR Creator')
    base_fair = fields.Char(string='Base Fair')
    sale_statement_status = fields.Char(string='Sale Statement Status')
    taxes = fields.Char(string='Taxes')
    tax_a3 = fields.Char(string='Tax A3')
    tax_ac = fields.Char(string='Tax AC')
    tax_ae = fields.Char(string='Tax AE')
    iata_passenger_type = fields.Char(string='IATA Passenger Type')
    passenger_civility = fields.Char(string='Passenger Civility')
    passenger_surname = fields.Char(string='Passenger Surname')
    passenger_first_name = fields.Char(string='Passenger First name')
    nationality = fields.Char(string='Nationality')
    date_of_birth = fields.Date(string='Date of Birth')
    place_of_birth = fields.Char(string='Place of Birth')
    passport_number = fields.Char(string='Passport Number')
    email_address = fields.Char(string='Email Address')
    mobile_number = fields.Char(string='Mobile Number')
    flight_number = fields.Char(string='Flight Number')
    flight_date = fields.Date(string='Flight Date')
    class_of_service = fields.Char(string='Class of service')
    booking_class = fields.Char(string='Booking Class')
    coupon_status = fields.Char(string='Coupon Status')
    aircraft_type = fields.Char(string='Aircraft Type')
    commission = fields.Char(string='Commission')
    discount = fields.Char(string='Discount')
    tour_code_discount = fields.Char(string='Tour Code Discount')
    adjustment = fields.Char(string='Adjustment')
    penalty = fields.Char(string='Penalty')
    acm = fields.Char(string='Agency Credit Memo')
    adm = fields.Char(string='Agency Debit Memo')
    baggage_supplement = fields.Char(string='Baggage Supplement')
    baggage_supplement_cancelation = fields.Char(string='Baggage Supplement Cancelation')
